# Generated by Django 6.0.5 on 2026-05-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('user_type', models.CharField(choices=[('driver', 'Driver'), ('admin', 'Admin')], default='driver', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('banned', 'Banned')], default='active', max_length=16)),
                ('moderation_notes', models.TextField(blank=True, default='')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=20)),
                ('national_id', models.CharField(max_length=100, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('vehicle_type', models.CharField(choices=[('boda', 'Boda'), ('bicycle', 'Bicycle'), ('van', 'Van'), ('truck', 'Truck'), ('car', 'Car')], max_length=20)),
                ('vehicle_make', models.CharField(blank=True, max_length=100)),
                ('vehicle_model', models.CharField(blank=True, max_length=100)),
                ('vehicle_color', models.CharField(blank=True, max_length=50)),
                ('vehicle_year', models.PositiveIntegerField(blank=True, null=True)),
                ('license_plate', models.CharField(max_length=50, unique=True)),
                ('id_doc', models.FileField(upload_to='kyc/id_docs/')),
                ('license_doc', models.FileField(upload_to='kyc/license_docs/')),
                ('vehicle_photo', models.ImageField(blank=True, null=True, upload_to='kyc/vehicle_photos/')),
                ('profile_photo', models.ImageField(upload_to='kyc/profile_photos/')),
                ('insurance_doc', models.FileField(blank=True, null=True, upload_to='kyc/insurance_docs/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('onboarding_paid', models.BooleanField(default=False)),
                ('onboarding_reference', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kycs', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Submission',
                'verbose_name_plural': 'KYC Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
