# Generated by Django 6.0.5 on 2026-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycsubmission',
            name='slug',
            field=models.SlugField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
